-- 코드를 입력하세요
# SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
# FROM REST_REVIEW B JOIN MEMBER_PROFILE A
# ON A.MEMBER_ID = B.MEMBER_ID
# WHERE A.MEMBER = (SELECT MEMBER_NAME
#                  FROM REST_REVIEW
#                  GROUP BY MEMBER_ID)
# SELECT COUNT(*), MEMBER_ID
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC
# LIMIT 1

WITH RANKINGS AS (
SELECT MEMBER_ID, RANK() OVER(ORDER BY count(*) DESC) AS RANKING
FROM REST_REVIEW
GROUP BY 1)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m ON r.MEMBER_ID = m.MEMBER_ID
WHERE m.MEMBER_ID IN (SELECT MEMBER_ID 
                      FROM RANKINGS 
                      WHERE RANKING = 1)
ORDER BY 3, 2